added a hack to fix ODIN compilation
the following compile error occurs with mbed-cloud-client 1.2.2-EA and
mbed-os 5.5.4:

Link: fota-demo
./BUILD/UBLOX_EVK_ODIN_W2/GCC_ARM/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/RTOS/pal_rtos.o: In function `pal_osGetDeviceKey':
pal_rtos.c:(.text.pal_osGetDeviceKey+0x2c): undefined reference to `pal_plat_osGetRoT128Bit'
collect2: error: ld returned 1 exit status
[ERROR] ./BUILD/UBLOX_EVK_ODIN_W2/GCC_ARM/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules/RTOS/pal_rtos.o: In function `pal_osGetDeviceKey':
pal_rtos.c:(.text.pal_osGetDeviceKey+0x2c): undefined reference to `pal_plat_osGetRoT128Bit'
collect2: error: ld returned 1 exit status

a workaround for this issue exists in
mbed-cloud-client-example-restricted for mbed-cloud-client 1.2.2-EA
in which a new file that provides an unsecure implementation of the
missing function is added.

the file is copied here.

not sure yet which project to log a bug against.

Signed-off-by: Nic Costa <nic.costa@arm.com>